extern void __ESBMC_assume(_Bool);
/*
 * AUTO-GENERATED BY verify-equiv v2.
 *
 * Neither placeholder is an implementation.
 *
 * After GOTO merge:
 *
 *   __ESBMC_PY_TARGET -> real Python GOTO function
 *   __ESBMC_C_TARGET  -> real C GOTO function
 */

extern int __VERIFIER_nondet_int(void);

/*
 * Complete Python frontend/module entry preserved by the
 * relational GOTO linker.
 *
 * This establishes static-lifetime/module/runtime state before
 * a symbolic request enters the translated function.
 */
extern void __ESBMC_PY_MODULE_ENTRY(void);

extern long __ESBMC_PY_TARGET(long e0, long e1, long e2, long e3);
extern int  __ESBMC_C_TARGET(int e0, int e1, int e2, int e3);

int equiv_main(void)
{
    /*
     * Python frontend semantics include module/static/runtime
     * initialization.  Do not jump directly into the Python target.
     */
    __ESBMC_PY_MODULE_ENTRY();

    int e0 = __VERIFIER_nondet_int();
    int e1 = __VERIFIER_nondet_int();
    int e2 = __VERIFIER_nondet_int();
    int e3 = __VERIFIER_nondet_int();
    __ESBMC_assume(e0 >= 0);
    __ESBMC_assume(e0 <= 255);
    __ESBMC_assume(e1 >= 0);
    __ESBMC_assume(e1 <= 255);
    __ESBMC_assume(e2 >= 0);
    __ESBMC_assume(e2 <= 255);
    __ESBMC_assume(e3 >= 0);
    __ESBMC_assume(e3 <= 255);


    long r_py =
        (long)__ESBMC_PY_TARGET((long)e0, (long)e1, (long)e2, (long)e3);

    long r_c =
        (long)__ESBMC_C_TARGET(e0, e1, e2, e3);

    __ESBMC_assert(
        r_py == r_c,
        "__VERIFY_EQUIV_RELATIONAL_PROPERTY__"
    );

    return 0;
}

int main(void)
{
    return equiv_main();
}
