extern void __ESBMC_assume(_Bool);
/*
 * AUTO-GENERATED BY verify-equiv v2.
 *
 * Neither placeholder is an implementation.
 *
 * After GOTO merge:
 *
 *   __ESBMC_PY_TARGET -> real Python GOTO function
 *   __ESBMC_C_TARGET  -> real C GOTO function
 */

extern int __VERIFIER_nondet_int(void);

/*
 * Complete Python frontend/module entry preserved by the
 * relational GOTO linker.
 *
 * This establishes static-lifetime/module/runtime state before
 * a symbolic request enters the translated function.
 */
extern void __ESBMC_PY_MODULE_ENTRY(void);

extern long __ESBMC_PY_TARGET(long n);
extern int  __ESBMC_C_TARGET(int n);

int equiv_main(void)
{
    /*
     * Python frontend semantics include module/static/runtime
     * initialization.  Do not jump directly into the Python target.
     */
    __ESBMC_PY_MODULE_ENTRY();

    int n = __VERIFIER_nondet_int();
    __ESBMC_assume(n >= 6);
    __ESBMC_assume(n <= 6);


    long r_py =
        (long)__ESBMC_PY_TARGET((long)n);

    long r_c =
        (long)__ESBMC_C_TARGET(n);

    __ESBMC_assert(
        r_py == r_c,
        "__VERIFY_EQUIV_RELATIONAL_PROPERTY__"
    );

    return 0;
}

int main(void)
{
    return equiv_main();
}
